version: "3.9"
services:
  stencil:
    build:
      context: ./env/node_stencil
    image: stencil_${THEME}
    container_name: stencil_${THEME}
    ports:
      - 3000:3000
    command:
      - stencil.sh
    volumes:
      - ./theme:/theme
    environment:
      - "STENCIL=${STENCIL}"
      - "STORE_URL=${STORE_URL}"
      - "API_TOKEN=${API_TOKEN}"