version: "3.9"
services:
  stencil_node:
    build:
      context: ./env/node
    image: stencil_node
    container_name: mtr_stencil_node
    ports:
      - 3000:3000
    volumes:
      - ./src:/theme
    command: start
    environment:
      - "S=${S}"