version: "3.9"
services:
  stencil_node:
    build:
      context: ./env/stencil_node
    image: stencil_node
    container_name: stencil_node
    ports:
      - 3000:3000
    volumes:
      - ./themes/${THEME}:/theme
    environment:
      - "STENCIL=${STENCIL}"