version: "3.9"
services:
  stencil:
    build:
      context: ./env/node_stencil
    image: stencil_dev
    container_name: stencil_dev
    ports:
      - 3000:3000
    command:
      - stencil.sh
    volumes:
      - ./theme:/theme
    environment:
      - "STENCIL=${STENCIL}"