version: "3.9"
services:
  stencil_node:
    build:
      context: ./env/node
    image: stencil_node
    container_name: stencil_node
    ports:
      - 3000:3000
      - 8181:8181
    volumes:
      - ./themes/${T}:/theme
    command: start
    environment:
      - "S=${S}"